sudo: required
language: node_js
node_js: "6"

matrix:
  include:
  # - os: linux
  - dist: trusty
  - os: osx
    osx_image: xcode8

install:
  - npm install
  # Install Wine and Mono to build the Windows version.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils;
  sudo add-apt-repository ppa:ubuntu-wine/ppa -y;
  sudo apt-get update;
  sudo apt-get install --no-install-recommends -y wine1.8;
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
  echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list;
  sudo apt-get update;
  sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono;
  fi

  # Install Wine for Mac.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  brew update;
  brew install gnu-tar libicns graphicsmagick xz;
  brew install wine --without-x11;
  brew install mono;
  fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist-linux; npm run dist-win; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist; fi
