sudo: true

language: node_js
node_js: "6"

os:
  - linux
  - osx

install:
  - npm install
  # Install wine to build the Windows version.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-wine/ppa; sudo apt-get update; sudo apt-get install -y wine1.8 winetricks; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install wine; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist; fi
