sudo: true

language: node_js
node_js: "6"

os:
  - linux
  - osx

install:
  - npm install
  # Install wine to build the Windows version.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386; sudo add-apt-repository -y ppa:wine/wine-builds; sudo apt-get -y update; sudo apt-get install -y --install-recommends winehq-devel; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist-linux; npm run dist-win; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist-mac; fi
