# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
  # node.js
    - nodejs_version: "6"

platform:
  - x86
  - x64

build: off

# scripts that run after cloning repository
install:
  - sh docker run --rm -ti -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:wine
  - /bin/bash -c "npm install && npm prune && npm run dist"
