# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
  # node.js
    - nodejs_version: "4"

platform:
  - x86
  - x64

build: off

# scripts that run after cloning repository
install:
  - npm install
  - npm run gulp
  # - npm run dist-win
